server:
  port: 8888
  #ssl:
  #  key-store: classpath:olibillKeystore.keystore
  #  key-alias: olibillKeystore
  servlet:
    application-display-name: PSOLIBILL- PROVINCE
    context-path: /prov

spring:
   main:
     allow-bean-definition-overriding: true
   messages:
     fallback-to-system-locale: true
     encoding: ISO-8859-1
   servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      file-size-threshold: 0B # Threshold after which files are written to disk.
      location: ${user.dir} # Intermediate location of uploaded files.
      max-file-size: 5MB # Max file size.
      max-request-size: 16MB # Max request size.
      resolve-lazily: false # Whether to resolve the multipart request lazily at the time of file or parameter access.
   h2:
     console:
        enabled: true
        path : /h2-console
   datasource:
       url: jdbc:h2:~/olibilldb/olibillprovincedb;AUTO_SERVER=TRUE #; DATABASE_TO_UPPER=false #jdbc:h2:~/olibilldb;AUTO_SERVER=TRUE
       platform: h2
       data: classpath:data/provinces.sql #classpath:data/taxes.sql, classpath:data/provinces.sql, classpath:data/taxesprovinces.sql #, classpath:reviews.sql
   jpa:
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
         ddl-auto: create-drop #update

# SOLIBILL's application details
management:
  #port: 8183
  #address: localhost
  #context-path: /solibillinfo
  server:
    address: localhost
    port: 8184 
    servlet:
      context-path: /solibill-provinfo
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
      
#endpoints:
#  info:
#    enabled: true
#    sensitive: false
#    id: info
#  sensitive: false
#  shutdown:
#    sensitive: false
#    enabled: true
    
info:
  app:
    description: Service prestation online bill creator
    version: 1.0 

logging:
  file: /olibilllogs/province.log
  #path: /olibilllogs
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    io:
      netty: DEBUG
    reactor: DEBUG