server:
  port: 8888
  #ssl:
  #  key-store: classpath:olibillKeystore.keystore
  #  key-alias: olibillKeystore
  servlet:
    application-display-name: PSOLIBILL- PROVINCE
    context-path: /prov

spring:
   application:
     name: Province et térritoires du Canada
   main:
     allow-bean-definition-overriding: true
   messages:
     fallback-to-system-locale: true
     encoding: ISO-8859-1
   servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      file-size-threshold: 0B # Threshold after which files are written to disk.
      location: ${user.dir} # Intermediate location of uploaded files.
      max-file-size: 5MB # Max file size.
      max-request-size: 16MB # Max request size.
      resolve-lazily: false # Whether to resolve the multipart request lazily at the time of file or parameter access.
   r2dbc:
    #url: r2dbc:h2:file://././olibilldb/olibillprovincedb?options=DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE  #?options=AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE #?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE #r2dbc:h2:file///olibilldb/olibillprovincedb
    #driver: io.r2dbc:r2dbc-h2
    name:
    password:
    #properties:
      #schema: classpath:schema.sql
    pool:
      enabled: true
      max-size: 30
      #max-idle-time: -1
   h2:
     console:
        enabled: true
        path : /h2-console
    #datasource:
     #sql:
       #init:
         #data-locations:
         #- classpath:data/provinces.sql
    #init:
       #platform: h2
     #url: jdbc:h2:~/olibilldb/olibillprovincedb;AUTO_SERVER=TRUE #; DATABASE_TO_UPPER=false #jdbc:h2:~/olibilldb;AUTO_SERVER=TRUE
  
    
    #platform: h2
    #data: classpath:data/provinces.sql #classpath:data/taxes.sql, classpath:data/provinces.sql, classpath:data/taxesprovinces.sql #, classpath:reviews.sql
    #jpa:
      #database-platform: org.hibernate.dialect.H2Dialect
      #hibernate:
        #  ddl-auto: create-drop #update
# SOLIBILL's application details
management:
  #port: 8183
  #address: localhost
  #context-path: /solibillinfo
  server:
    address: localhost
    base-path: /solibill-provinfo
    port: 8184 
    #cservlet:
      #ccontext-path: /solibill-provinfo
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
      
#endpoints:
#  info:
#    enabled: true
#    sensitive: false
#    id: info
#  sensitive: false
#  shutdown:
#    sensitive: false
#    enabled: true
    
info:
  app:
    description: Service prestation online bill creator
    version: 1.0 

logging:
  file:
    name: /olibilllogs/province.log
  #path: /olibilllogs
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    io:
      netty: DEBUG
    reactor: DEBUG